### ISSUE TITLE
[🐞] Every component on the page is frozen during async useTask$

### ISSUE THREAD

**Issue by cmbartschat** [QwikDev/qwik#2672]
### Which component is affected?

Qwik Runtime

### Describe the bug

It seems unexpected that a framework that stresses the importance of async rendering has this sort of full freeze during useTask, though if the component running the task itself has to be frozen, that is more expected, though still not optimal.

In terms of real world conditions, this might also occur during the network fetch of the useTask function, which would be surprising I think.

### Reproduction

```
https://qwik.builder.io/playground#version=0.17.5&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdXNlQ2xpZW50RWZmZWN0JTI0JTJDJTIwdXNlU3RvcmUlMjAlMkMlMjBjb21wb25lbnQlMjQlMkMlMjB1c2VTaWduYWwlMkMlMjB1c2VUYXNrJTI0JTJDJTIwU2xvdCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWsnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHNsZWVwJTIwJTNEJTIwKG1zJTNBJTIwbnVtYmVyKSUyMCUzRCUzRSUyMG5ldyUyMFByb21pc2UoKHIpJTIwJTNEJTNFJTIwc2V0VGltZW91dChyJTJDJTIwbXMpKSUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBCb3glMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTIwc3R5bGUlM0QlN0IlN0Jib3JkZXIlM0ElMjAnMXB4JTIwc29saWQlMjBncmF5JyUyQyUyMG1hcmdpbiUzQSUyMCc4cHgnJTJDJTIwcGFkZGluZyUzQSUyMCc4cHgnJTdEJTdEJTNFJTVDbiUyMCUyMCUzQ1Nsb3QlMjAlMkYlM0UlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2FpdGVyJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwc3RvcmUlMjAlM0QlMjB1c2VTdG9yZSglN0JpbnB1dCUzQSUyMCcnJTJDJTIwaXNUaGlua2luZyUzQSUyMGZhbHNlJTJDJTIwcmVzdWx0JTNBJTIwMCU3RCklNUNuJTVDbiUyMCUyMHVzZVRhc2slMjQoYXN5bmMlMjAoY3R4KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMGlucHV0JTIwJTNEJTIwY3R4LnRyYWNrKCgpJTIwJTNEJTNFJTIwc3RvcmUuaW5wdXQpJTVDbiUyMCUyMCUyMCUyMHN0b3JlLmlzVGhpbmtpbmclMjAlM0QlMjAlMjB0cnVlJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwc2xlZXAoTWF0aC5yYW5kb20oKSUyMColMjAzMDAwKSU1Q24lMjAlMjAlMjAlMjBzdG9yZS5pc1RoaW5raW5nJTIwJTNEJTIwZmFsc2UlNUNuJTIwJTIwJTIwJTIwc3RvcmUucmVzdWx0JTIwJTNEJTIwaW5wdXQubGVuZ3RoJTVDbiUyMCUyMCU3RCklNUNuJTVDbiUyMCUyMHJldHVybiUyMCUzQ0JveCUzRSU1Q24lMjAlMjAlM0NpbnB1dCUyMHZhbHVlJTNEJTdCc3RvcmUuaW5wdXQlN0QlMjBvbklucHV0JTI0JTNEJTdCKGUpJTIwJTNEJTNFJTIwc3RvcmUuaW5wdXQlMjAlM0QlMjAoZS50YXJnZXQlMjBhcyUyMGFueSkudmFsdWUlN0QlMjAlMkYlM0UlNUNuJTIwJTIwJTNDcCUzRSU3QnN0b3JlLmlzVGhpbmtpbmclMjAlM0YlMjAnVGhpbmtpbmcnJTIwJTNBJTIwJ0xlbmd0aCUyMGlzJTNBJTIwJyUyMCUyQiUyMHN0b3JlLnJlc3VsdCU3RCUyMCUyMCUzQyUyRnAlM0UlNUNuJTIwJTIwJTNDJTJGQm94JTNFJTNCJTVDbiU3RCklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQ291bnRlciUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHNpZ25hbCUyMCUzRCUyMHVzZVNpZ25hbCgwKSU1Q24lMjAlMjB1c2VDbGllbnRFZmZlY3QlMjQoKGN0eCklMjAlM0QlM0UlN0IlNUNuJTIwJTIwJTIwJTIwJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwaW50ZXJ2YWwlMjAlM0QlMjBzZXRJbnRlcnZhbCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBzaWduYWwudmFsdWUlMjAlMkIlMkIlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTIwNTAwKSU1Q24lNUNuJTIwJTIwJTIwJTIwY3R4LmNsZWFudXAoKCklMjAlM0QlM0UlMjBjbGVhckludGVydmFsKGludGVydmFsKSklNUNuJTIwJTIwJTdEKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFQ291bnRlciUzQSUyMCU3QnNpZ25hbC52YWx1ZSU3RCUzQyUyRmRpdiUzRSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDQm94JTIwJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ0NvdW50ZXIlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDV2FpdGVyJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRkJveCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE
```

### Steps to reproduce

- Open the playground
- Type in the text box
- Even though the Counter is outside the component performing the useTask, it stops updating while we're waiting for the task to complete

### System Info

```shell
Qwik Playground/Firefox/Windows
```

**Comment by manucorporat** [comment]
It's a perfectly solvable problem, we never got to it, cuz we have alternatives that require no blocking. But fully agree this is something to solve.

Requires some design work, because it still needs to satisfy some constrains like deterministic tree renders, we can't just run everything in parallel.

I would recomend to use `useResource$()` to compute values that you need in your component, useResource$() is always fully parallel:

https://qwik.builder.io/playground#version=0.16.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdXNlQ2xpZW50RWZmZWN0JTI0JTJDJTIwdXNlU3RvcmUlMjAlMkMlMjBjb21wb25lbnQlMjQlMkMlMjBSZXNvdXJjZSUyQyUyMHVzZVNpZ25hbCUyQyUyMHVzZVJlc291cmNlJTI0JTJDJTIwU2xvdCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWsnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHNsZWVwJTIwJTNEJTIwKG1zJTNBJTIwbnVtYmVyKSUyMCUzRCUzRSUyMG5ldyUyMFByb21pc2UoKHIpJTIwJTNEJTNFJTIwc2V0VGltZW91dChyJTJDJTIwbXMpKSUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBCb3glMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTIwc3R5bGUlM0QlN0IlN0Jib3JkZXIlM0ElMjAnMXB4JTIwc29saWQlMjBncmF5JyUyQyUyMG1hcmdpbiUzQSUyMCc4cHgnJTJDJTIwcGFkZGluZyUzQSUyMCc4cHgnJTdEJTdEJTNFJTVDbiUyMCUyMCUzQ1Nsb3QlMjAlMkYlM0UlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2FpdGVyJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwaW5wdXQlMjAlM0QlMjB1c2VTaWduYWwoJycpJTNCJTVDbiU1Q24lMjAlMjBjb25zdCUyMHJlc291cmNlJTIwJTNEJTIwdXNlUmVzb3VyY2UlMjQlM0NudW1iZXIlM0UoYXN5bmMlMjAoY3R4KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMHZhbHVlJTIwJTNEJTIwY3R4LnRyYWNrKCgpJTIwJTNEJTNFJTIwaW5wdXQudmFsdWUpJTNCJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwc2xlZXAoTWF0aC5yYW5kb20oKSUyMColMjAzMDAwKSUzQiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB2YWx1ZS5sZW5ndGglM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDQm94JTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdmFsdWUlM0QlN0JpbnB1dC52YWx1ZSU3RCUyMG9uSW5wdXQlMjQlM0QlN0IoZSklMjAlM0QlM0UlMjBpbnB1dC52YWx1ZSUyMCUzRCUyMChlLnRhcmdldCUyMGFzJTIwYW55KS52YWx1ZSU3RCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NSZXNvdXJjZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzRCU3QnJlc291cmNlJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG9uUGVuZGluZyUzRCU3QigpJTIwJTNEJTNFJTIwJTNDcCUzRVRoaW5raW5nJTNDJTJGcCUzRSU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjBvblJlc29sdmVkJTNEJTdCKHZhbHVlKSUyMCUzRCUzRSUyMCUzQ3AlM0VMZW5ndGglMjBpcyUzQSUyMCU3QnZhbHVlJTdEJTNDJTJGcCUzRSU3RCU1Q24lMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTIwJTIwJTNDJTJGQm94JTNFJTVDbiU3RCklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQ291bnRlciUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHNpZ25hbCUyMCUzRCUyMHVzZVNpZ25hbCgwKSU1Q24lMjAlMjB1c2VDbGllbnRFZmZlY3QlMjQoKGN0eCklMjAlM0QlM0UlN0IlNUNuJTIwJTIwJTIwJTIwJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwaW50ZXJ2YWwlMjAlM0QlMjBzZXRJbnRlcnZhbCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBzaWduYWwudmFsdWUlMjAlMkIlMkIlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTIwNTAwKSU1Q24lNUNuJTIwJTIwJTIwJTIwY3R4LmNsZWFudXAoKCklMjAlM0QlM0UlMjBjbGVhckludGVydmFsKGludGVydmFsKSklNUNuJTIwJTIwJTdEKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFQ291bnRlciUzQSUyMCU3QnNpZ25hbC52YWx1ZSU3RCUzQyUyRmRpdiUzRSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDQm94JTIwJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ0NvdW50ZXIlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDV2FpdGVyJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRkJveCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

**Comment by cmbartschat** [comment]
Thanks for the clarification! 

Something that could help my understanding is to know, would switching to useResource been a viable approach for [this PR](https://github.com/BuilderIO/qwik/pull/2661/files#diff-9573e0d01ae627683e7f359a75cae46d32115e5d2fdf263fb71b3a7761d75a98R210)? I could see a side effect vs no side effect criterion but let me what you think.

**Comment by frammiie** [comment]
The way `useClientEffect`'s are handled seems similar, execution halts per component
and handlers are executed sequentially.

This is rather unfortunate, since this introduces significant slowdown for components
that contain processing.

**Comment by jdgamble555** [comment]
In react, you don't usually use `async` inside `useEffect`.  You just use `then` to get what you need:

```js
useClientEffect(() => {
  somefetchfunction()
    .then((r) => {
     // do something
    });
});
```
Not sure if this is relevant to this conversation, but I suspect you could just use a signal or store to save the data in a custom hook, then return that signal.

May not be related, but just my thoughts...

J

**Comment by DustinJSilk** [comment]
Is there ever a time where we want an async task if it blocks rendering? Could we then add an eslint rule or automatically wrap async callbacks in an IIFE?

**Comment by gioboa** [comment]
This issue is stale, there are few solutions though.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
