### ISSUE TITLE
[🐞] Click-to-Source not working on Windows

### ISSUE THREAD

**Issue by tuurbo** [QwikDev/qwik#3710]
### Which component is affected?

Qwik Runtime

### Describe the bug

The Click-to-Source debug feature stopped working for me a few weeks ago. If I try to click an element with `alt+click` I get a chrome console error ```Not allowed to load local resource: file:///C:/_work/websites/qwik-error/src/routes/layout.tsx:21:9``` and it doesn't open the file in vscode.

It works with stackblitz but not on my local machine. I'm on Windows 10.

### Reproduction

n/a

### Steps to reproduce

pnpm create qwik
pnpm dev
try to Alt-click something
see error in chrome console

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 16.15 GB / 31.68 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/partytown: ^0.7.6 => 0.7.6
    @builder.io/qwik: 0.101.0 => 0.101.0
    @builder.io/qwik-city: 0.101.0 => 0.101.0
    vite: 4.2.1 => 4.2.1
```

### Additional Information

n/a

**Comment by Grimshire** [comment]
Super in factor of that!

**Comment by barel-mishal** [comment]
in my end it is working but not good experiences it does get show me the source but, on the terminal, not the vs code like I want to. hope fully another person has it too and know how to fix that.

**Comment by irg1008** [comment]
It's such a cool feature. And It doesn't seem to be hard to pinpoint. Do we know where in the code this feature is implemented so I can peek around (I mainly use windows)

**Comment by adamdbradley** [comment]
Thanks @irg1008! The source can be found here: https://github.com/BuilderIO/qwik/blob/47c4de6465dfce48220b1e1cf5e1c92ec9e43b85/packages/qwik/src/optimizer/src/plugins/vite-server.ts#L384

**Comment by bemayr** [comment]
## Problem Analysis

I just stumbled over this problem while wanting to try out qwik. Thanks @adamdbradley for linking the source, I just did some digging and found out that the problem originates from these lines of code:
```js
  const origin = 'http://local.local';
  const srcDir = new URL(${JSON.stringify(srcDir + '/')}, origin);
  // [...]
  const resolvedURL = new URL(event.target.dataset.qwikInspector, srcDir);
  // [...]
  if (resolvedURL.origin === origin) {
    // 🎯 this should be entered so that the editor can be launched
    // [...]
    // 💥 `pathname` is also a problem here on Windows, because **it strips the drive letter**
    params.set('file', resolvedURL.pathname);
    // [...]
  } else {
    // 💥 this is entered, leading to the warning/error because of trying to open the file via href
    location.href = resolvedURL.href;
}
```

I don't know why this origin check was introduced at first, but the main problem is the difference of `new URL(...)` betweeen a Windows-like file path and a Unix one:

While the drive-prefixed version `new URL("C:/path/to/somewhere/", origin)` leads to
```json
{
  "href": "c:/path/to/somewhere/",
  "origin": "null",
  "protocol": "c:",
  "host": "",
  "hostname": "",
  "pathname": "/path/to/somewhere/"
}
```

the non-prefixed one `new URL("/path/to/somewhere/", origin)` leads to
```json
{
  "href": "http://local.local/path/to/somewhere/",
  "origin": "http://local.local",
  "protocol": "http:",
  "host": "local.local",
  "hostname": "local.local",
  "pathname": "/path/to/somewhere/"
}
```

This of course breaks the `if`, because of the non-matching `origin`-values.

## Tested Solution
Calling `http://localhost:5173/__open-in-editor?file=c:/path/to/somewhere/component.tsx:1:42` provides the expected result.

## Further Steps
- Building upon this knowledge, we should find a solution that includes the drive letter, if on was specified.
- Does somebody know why the origin check is there?
- Which problems might arise of not using `origin` at all and directly using `href`?

**Comment by pashaie** [comment]
Still not working in windows 
OS: windows 11
@builder.io/qwik: "^1.2.6",

any updates?

**Comment by Grimshire** [comment]
Dang, well done man!

**Comment by wmertens** [comment]
@pashaie can you not include this change in qwik itself?

**Comment by irg1008** [comment]
A year!! My god we really hate windows don't we haha

**Comment by PatrickJS** [comment]
well we were hoping others would fix it (for more contributions). I'm going through and cleaning up all the old issues 😅 if you find any more windows issues let me know or anything that should be fixed/reworded in the docs I'll get it merged

**Comment by burgil** [comment]
Hi, Sorry to bump a closed issue but I found something useful since I also had this issue ever since I started using Qwik a few days ago, and this issue is first on google when you search for `Click-to-Source qwik windows`.

Since it is also embedded in the tutorials, I thought hey why everyone have it and I don't, haha, was determined to find the problem in my vite/tsconfig/qwik/idk configuration, since I assumed it had to be something with me, but people here did not seem to find a solution so I had to dig deeper, so I ended up making a patch to `vite` itself at the end, lol.

I'm on Windows, worked hard to find a temporary solution, didn't want to add a visible task that will get packaged to production as suggested above.

**Note: Scroll all the way down to skip to the solution (for vite v6.0.1 on Windows - Worked for me, may not work for you, use at your own risk)**

# The issue

So, In my case I noticed in the network tab on the devtools that when I `alt+click` on an element it redirects to:
```
http://localhost:5173/__open-in-editor?file=a%3A%2FProjects%2Fmyapp%2Ffrontend%2Fsrc%2F%2Fsrc%2Fcomponents%2Fstarter%2Fhero%2Fhero.tsx%3A12%3A17
```

**Decoded string:** `a:/Projects/myapp/frontend/src//src/components/starter/hero/hero.tsx:12:17`

Notice that the `src` folder appears twice,
So I thought if only I can find a way to modify it then I might just get it to work.. And it did!

I googled for a solution and saw this issue before I started,
Decided to come back and share my findings now that I found a solution.

Before I've found the solution, I tried anything I could think of,
For example did you know you can literally access this variable from the devtools via:

```js
console.log(globalThis.qwikdevtools.srcDir);
```

So in one of my failed attempts I even tried modifying it like so but that didn't affect it since the code already ran:
```js
const splitDir = globalThis.qwikdevtools.srcDir.split('/');
let fixedDir = splitDir.splice(0, splitDir.length - 3).join('/')
if (fixedDir[fixedDir.length - 1] !== '/') fixedDir = fixedDir + '/';
globalThis.qwikdevtools.srcDir = fixedDir;
```

Or that you can specify an srcDir to the `qwikVite()` plugin options in `vite.config.ts`

But these solutions, and many others, simply did not work for me, and the site was still sending requests to what appears to be, at the end of the day, `src//src`.

After exploring a bit I found out there is a [middleware](https://www.npmjs.com/package/launch-editor-middleware) mounted on vite itself for the [launch editor](https://github.com/yyx990803/launch-editor), I use vite v6.0.1

And although it's being invoked from `@builder.io/qwik` somewhere in `@builder.io\qwik\dist\optimizer.mjs/cjs` along the lines:
```
 const isWindows = navigator.platform.includes('Win');\n      const resolvedURL = new URL(path, isWindows ? origin : srcDir);\n      if (resolvedURL.origin === origin) {\n        const params = new URLSearchParams();\n        const prefix = isWindows ? srcDir : '';\n        params.set('file', prefix + resolvedURL.pathname);\n        fetch('/__open-in-editor?' + params.toString());\
 ```
 
I decided to create my first [patch](https://stackoverflow.com/questions/72820625/what-is-the-proper-way-to-patch-a-node-modules-module), since I already managed to manually debug the area that causes the issue in `vite/dist/node/chunks/dep-BcnkIxro.js`, I decided this is the file I am going to patch.

**The plan was simple:** replace `src//src` with `src`, unfortunately the `npx patch-package vite` command only works on `npm` and `yarn`, but I use `pnpm`, so a quick google led me [here](https://pnpm.io/cli/patch), where I finally created the patch and solved the issue. And now I am having the best time of my life with this awesome new feature!

**Note:** Luckily the file named `dep-BcnkIxro.js` does not change after you delete `node_modules` and reinstall, and the patch is applied automatically, so I will simply need to maintain this patch for every new vite version until the issue is fixed at the root.

Hopefully my findings, the duplicated use of `src`, can be a lead towards the underlying issue.

**Thanks for everyone involved in this project I love it, good luck!**

# How I created the patch

Incase vite will update or you want to manually do it then it is important to share the steps of how to create the patch in the first place:

1. Before you start modifying vite, run `pnpm patch vite`.
2. This will generate inside the `node_modules` a folder named `.pnpm_patches` and inside there you will find a copy of `vite`
3. Modify the files you want and then run the command provided in the terminal when you started:
e.g. `pnpm patch-commit 'A:\Projects\myapp\frontend\node_modules\.pnpm_patches\vite@6.0.1'`
4. The `package.json` file will be automatically modified with the `patchedDependencies` and a new folder will be created at the root of the project named `patches` with the vite patch inside of it
5. Alt+clicking on windows works now
6. You can try to delete `node_modules` and then run `pnpm i` or `pnpm install`, the patches will be applied automatically and you now can `Alt+click` on windows, cheers 🎉

**How to manually apply the patch?**
1. `pnpm patch vite`
2. Go to `node_modules\.pnpm_patches\vite@6.0.1\dist\node\chunks\dep-BcnkIxro.js`
3. Find and modify these lines:
```diff
-      launch(path$3.resolve(srcRoot, file), specifiedEditor, onErrorCallback);
+      launch((path$3.resolve(srcRoot, file.replace('src//src', 'src'))), specifiedEditor, onErrorCallback);
```
4. Save and run the `pnpm patch-commit ...` command provided for you in the terminal after you ran the first command

# The solution

I fixed the issue using a patch made directly to vite itself, but it assumes you use `pnpm`, `windows` and `vite v6.0.1`:

(You can also manually follow the patch instructions for now)

**patches/vite.patch**
```
diff --git a/dist/node/chunks/dep-BcnkIxro.js b/dist/node/chunks/dep-BcnkIxro.js
index 8e79c71d27d3ecb51f2e7ed6715a23a9bdd0dd32..d216af0eca0c168e251b655e5a913d4be904331e 100644
--- a/dist/node/chunks/dep-BcnkIxro.js
+++ b/dist/node/chunks/dep-BcnkIxro.js
@@ -30304,7 +30304,7 @@ var launchEditorMiddleware = (specifiedEditor, srcRoot, onErrorCallback) => {
       res.statusCode = 500;
       res.end(`launch-editor-middleware: required query param "file" is missing.`);
     } else {
-      launch(path$3.resolve(srcRoot, file), specifiedEditor, onErrorCallback);
+      launch((path$3.resolve(srcRoot, file.replace('src//src', 'src'))), specifiedEditor, onErrorCallback);
       res.end();
     }
   }
```
**package.json**
```
	"packageManager": "pnpm@9.14.3",
	"pnpm": {
		"patchedDependencies": {
			"vite": "patches/vite.patch"
		}
	}
```
`pnpm i`

Done. It will just work now. well.. at least for me.

**Comment by irg1008** [comment]
> Hi, Sorry to bump a closed issue but I found something useful since I also had this issue ever since I started using Qwik a few days ago, and this issue is first on google when you search for `Click-to-Source qwik windows`.
> 
> 
> 
> Since it is also embedded in the tutorials, I thought hey why everyone have it and I don't, haha, was determined to find the problem in my vite/tsconfig/qwik/idk configuration, since I assumed it had to be something with me, but people here did not seem to find a solution so I had to dig deeper, so I ended up making a patch to `vite` itself at the end, lol.
> 
> 
> 
> I'm on Windows, worked hard to find a temporary solution, didn't want to add a visible task that will get packaged to production as suggested above.
> 
> 
> 
> **Note: Scroll all the way down to skip to the solution (for vite v6.0.1 on Windows - Worked for me, may not work for you, use at your own risk)**
> 
> 
> 
> # The issue
> 
> 
> 
> So, In my case I noticed in the network tab on the devtools that when I `alt+click` on an element it redirects to:
> 
> ```
> 
> http://localhost:5173/__open-in-editor?file=a%3A%2FProjects%2Fmyapp%2Ffrontend%2Fsrc%2F%2Fsrc%2Fcomponents%2Fstarter%2Fhero%2Fhero.tsx%3A12%3A17
> 
> ```
> 
> 
> 
> **Decoded string:** `a:/Projects/myapp/frontend/src//src/components/starter/hero/hero.tsx:12:17`
> 
> 
> 
> Notice that the `src` folder appears twice,
> 
> So I thought if only I can find a way to modify it then I might just get it to work.. And it did!
> 
> 
> 
> I googled for a solution and saw this issue before I started,
> 
> Decided to come back and share my findings now that I found a solution.
> 
> 
> 
> Before I've found the solution, I tried anything I could think of,
> 
> For example did you know you can literally access this variable from the devtools via:
> 
> 
> 
> ```js
> 
> console.log(globalThis.qwikdevtools.srcDir);
> 
> ```
> 
> 
> 
> So in one of my failed attempts I even tried modifying it like so but that didn't affect it since the code already ran:
> 
> ```js
> 
> const splitDir = globalThis.qwikdevtools.srcDir.split('/');
> 
> let fixedDir = splitDir.splice(0, splitDir.length - 2).join('/')
> 
> if (fixedDir[fixedDir.length - 1] !== '/') fixedDir = fixedDir + '/';
> 
> globalThis.qwikdevtools.srcDir = fixedDir;
> 
> ```
> 
> 
> 
> Or that you can specify an `srcDir` to the `qwikVite()` plugin options in `vite.config.ts`
> 
> 
> 
> But these solutions, and many others, simply did not work for me, and the site was still sending requests to what appears to be, at the end of the day, `src//src`.
> 
> 
> 
> After exploring a bit I found out there is a [middleware](https://www.npmjs.com/package/launch-editor-middleware) mounted on vite itself for the [launch editor](https://github.com/yyx990803/launch-editor), I use vite v6.0.1
> 
> 
> 
> And although it's being invoked from `@builder.io/qwik` somewhere in `@builder.io\qwik\dist\optimizer.mjs/cjs` along the lines:
> 
> ```
> 
>  const isWindows = navigator.platform.includes('Win');\n      const resolvedURL = new URL(path, isWindows ? origin : srcDir);\n      if (resolvedURL.origin === origin) {\n        const params = new URLSearchParams();\n        const prefix = isWindows ? srcDir : '';\n        params.set('file', prefix + resolvedURL.pathname);\n        fetch('/__open-in-editor?' + params.toString());\
> 
>  ```
> 
>  
> 
> I decided to create my first [patch](https://stackoverflow.com/questions/72820625/what-is-the-proper-way-to-patch-a-node-modules-module), since I already managed to manually debug the area that causes the issue in `vite/dist/node/chunks/dep-BcnkIxro.js`, I decided this is the file I am going to patch.
> 
> 
> 
> **The plan was simple:** replace `src//src` with `src`, unfortunately the `npx patch-package vite` command only works on `npm` and `yarn`, but I use `pnpm`, so a quick google led me [here](https://pnpm.io/cli/patch), where I finally created the patch and solved the issue. And now I am having the best time of my life with this awesome new feature!
> 
> 
> 
> **Note:** Luckily the file named `dep-BcnkIxro.js` does not change after you delete `node_modules` and reinstall, and the patch is applied automatically, so I will simply need to maintain this patch for every new vite version until the issue is fixed at the root.
> 
> 
> 
> Hopefully my findings, the duplicated use of `src`, can be a lead towards the underlying issue.
> 
> 
> 
> **Thanks for everyone involved in this project I love it, good luck!**
> 
> 
> 
> # How I created the patch
> 
> 
> 
> Incase vite will update or you want to manually do it then it is important to share the steps of how to create the patch in the first place:
> 
> 
> 
> 1. Before you start modifying vite, run `pnpm patch vite`.
> 
> 2. This will generate inside the `node_modules` a folder named `.pnpm_patches` and inside there you will find a copy of `vite`
> 
> 3. Modify the files you want and then run the command provided in the terminal when you started:
> 
> e.g. `pnpm patch-commit 'A:\Projects\myapp\frontend\node_modules\.pnpm_patches\vite@6.0.1'`
> 
> 4. The `package.json` file will be automatically modified with the `patchedDependencies` and a new folder will be created at the root of the project named `patches` with the vite patch inside of it
> 
> 
> 
> **How to manually apply the patch?**
> 
> 1. `pnpm patch vite`
> 
> 2. Go to `node_modules\.pnpm_patches\vite@6.0.1\dist\node\chunks\dep-BcnkIxro.js`
> 
> 3. Find and modify these lines:
> 
> ```diff
> 
> -      launch(path$3.resolve(srcRoot, file), specifiedEditor, onErrorCallback);
> 
> +      launch((path$3.resolve(srcRoot, file.replace('src//src', 'src'))), specifiedEditor, onErrorCallback);
> 
> ```
> 
> 4. Save and run the `pnpm patch-commit ...` command provided for you in the terminal after you ran the first command
> 
> 5. Alt+clicking on windows works now
> 
> 6. You can try to delete `node_modules` and then run `pnpm i` or `pnpm install`, the patches will be applied automatically and you now can `Alt+click` on windows, cheers 🎉
> 
> 
> 
> # The solution
> 
> 
> 
> I fixed the issue using a patch made directly to vite itself, but it assumes you use `pnpm`, `windows` and `vite v6.0.1`:
> 
> 
> 
> (You can also manually follow the patch instructions for now)
> 
> 
> 
> **patches/vite.patch**
> 
> ```
> 
> diff --git a/dist/node/chunks/dep-BcnkIxro.js b/dist/node/chunks/dep-BcnkIxro.js
> 
> index 8e79c71d27d3ecb51f2e7ed6715a23a9bdd0dd32..d216af0eca0c168e251b655e5a913d4be904331e 100644
> 
> --- a/dist/node/chunks/dep-BcnkIxro.js
> 
> +++ b/dist/node/chunks/dep-BcnkIxro.js
> 
> @@ -30304,7 +30304,7 @@ var launchEditorMiddleware = (specifiedEditor, srcRoot, onErrorCallback) => {
> 
>        res.statusCode = 500;
> 
>        res.end(`launch-editor-middleware: required query param "file" is missing.`);
> 
>      } else {
> 
> -      launch(path$3.resolve(srcRoot, file), specifiedEditor, onErrorCallback);
> 
> +      launch((path$3.resolve(srcRoot, file.replace('src//src', 'src'))), specifiedEditor, onErrorCallback);
> 
>        res.end();
> 
>      }
> 
>    }
> 
> ```
> 
> **package.json**
> 
> ```
> 
> 	"packageManager": "pnpm@9.14.3",
> 
> 	"pnpm": {
> 
> 		"patchedDependencies": {
> 
> 			"vite": "patches/vite.patch"
> 
> 		}
> 
> 	}
> 
> ```
> 
> `pnpm i`
> 
> 
> 
> Done. It will just work now. well.. at least for me.
> 
> 
> 
> Update: Also, I use VSCode insiders so I also had to `win> search for env > Edit the system environment variables > Environment Variables > New.. (Top) > Variable Name: LAUNCH_EDITOR > Variable value: code-insiders > Ok > Ok > Ok > Restart VSCode`

Now that's how you reply in a ghost issue, god tier

**Comment by vsDizzy** [comment]
Can we reopen this? I also facing double `/src//src` path.
I think this line needs to be fixed:
https://github.com/QwikDev/qwik/blob/0f1610b8e9125a289f4bd27734c33c6a80021d15/packages/qwik/src/optimizer/src/plugins/click-to-component.html#L150

**Comment by moonhuntercode** [comment]
> Can we reopen this? I also facing double `/src//src` path. I think this line needs to be fixed:
> 
> [qwik/packages/qwik/src/optimizer/src/plugins/click-to-component.html](https://github.com/QwikDev/qwik/blob/0f1610b8e9125a289f4bd27734c33c6a80021d15/packages/qwik/src/optimizer/src/plugins/click-to-component.html#L150)
> 
> Line 150 in [0f1610b](/QwikDev/qwik/commit/0f1610b8e9125a289f4bd27734c33c6a80021d15)
> 
>  const prefix = isWindows ? srcDir : '';

true, in my win11 not working too

**Comment by gioboa** [comment]
Thanks for the report @moonhuntercode 
In the network tab you should see an HTTP request with the path of the file to open.
What is wrong on that?
This check will help us to solve the specific issue with w11. Thanks
