### ISSUE TITLE
[📖] Security of Actions + Route vs Global Actions

### ISSUE THREAD

**Issue by fabian-hiller** [QwikDev/qwik#4081]
### Suggestion

Since the state of an action can be accessed via its ID in the URL parameters, I wonder if this can be a security issue. Can a person guess the action ID of another user? How is it ensured that actions do not leak data? I think a note about this in the docs would be useful.

Furthermore, the consequences of route vs global actions are not quite clear to me yet. What are the disadvantages, for example security-wise, of using `globalAction$` instead of `routeAction$`? I ask because `formAction$` from Modular Forms is currently based on `globalActionQrl` and here the disadvantages to `routeActionQrl` are not quite clear. Should I rather provide `routeActionForm$` and `globalActionForm$` separately instead of `formAction$`?

Issue at Modular Forms: https://github.com/fabian-hiller/modular-forms/issues/63

**Comment by mhevery** [comment]
Action is equivalent to making a POST to a URL. Anyone can do it. No explicit security is implied by it. It is the responsibility of the action to ensure that the post request has the right kind of cookie (or other auth mechanism). 

I will try to write  up some documentation on this.

**Comment by mhevery** [comment]
Global actions are the same as route actions, except they are not tied to any particular route.

**Comment by fabian-hiller** [comment]
Thank you @mhevery for the answer. Then why does `routeAction$` exist at all if `globalAction$` can be used instead and is not a disadvantage? Would you recommend Modular Forms to provide `routeActionForm$` and `globalActionForm$` seperately instead of `formAction$`?

Also, out of curiosity and also for security reasons, I would be interested to know how the state of an action is kept internally. How does the server know which state to use for which request. When I use Qwik with Modular Forms without JavaScript in the browser, the server keeps the state of the form. Technically this works beautifully, even across multiple tabs in the same browser. I'd like to understand how this works and how it prevents the state from being accidentally passed to a wrong request/user.

**Comment by mhevery** [comment]
You can think of `globalAction` as a `routeAction` at the highest Layout. (@manucorporat correct me if I am wrong on this)
The advantage of `globalAction` is that you can declare it in `plugin@___` file, and therefore it is separated from the layout file. Third parties can add actions without cluttering your top-level layout file. (Top-level layout can also be bypassed by `index!.tsx` but it will not bypass the `globalAction`)

The normal security model is that action is stateless, which means the data is usually stored in the client (in form.) For security, one should employ cookies.

**Comment by gioboa** [comment]
@fabian-hiller Can we close this one?

**Comment by maiieul** [comment]
Closing this since Fabian left a thumbs up 🙃

**Comment by shairez** [comment]
Just adding more context for future readers - 

`routeAction$` is more secure if you combine it with `auth.js`, meaning - if you declare it on a secured route it won't be able to get executed from a different route branch (unlike `globalAction$` which you can declare anywhere and if you know its ID you can from the root domain. 

That's why it's a best practice to use a `routeAction$` , even for libraries, and if they are being using in a component, to re-export them from that component parent route.

That way you'll achieve maximum security and provide users a safer way to build their apps.

FYI - in the end of the day, it's the responsibility of the end developer to secure their server functions, `routeAction$` + `auth.js` plugin just make it easier to do.
