### ISSUE TITLE
[🐞] vite incorectly processes `import.meta.env` in examples

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#4569]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. This line: https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/docs/labs/insights/index.mdx#L34
2. Generates:
![image](https://github.com/BuilderIO/qwik/assets/111951/0d9e92cc-391c-4a23-b824-0216fc57855a)
notice `({})` when it should be `import.meta.env`

### Reproduction

https://qwik.builder.io/docs/labs/insights/

### Steps to reproduce

Navigate to: https://qwik.builder.io/docs/labs/insights/
See: ![image](https://github.com/BuilderIO/qwik/assets/111951/0d9e92cc-391c-4a23-b824-0216fc57855a)
notice `({})` when it should be `import.meta.env`

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
it's almost like a vite / mdx issue

**Comment by TimKieu** [comment]
VITE: I also face this ENV with Vite React and Vite Hono/Express.
Vite cannot process import.meta.env or the older process.env

**Comment by gioboa** [comment]
🤔 that's because you need to call the env variables with the prefix VITE_

Extract from the [documentation](https://vitejs.dev/guide/env-and-mode.html#env-files)
-----
To prevent accidentally leaking env variables to the client, only variables prefixed with VITE_ are exposed to your Vite-processed code. e.g. for the following env variables:


VITE_SOME_KEY=123
DB_PASSWORD=foobar
Only VITE_SOME_KEY will be exposed as import.meta.env.VITE_SOME_KEY to your client source code, but DB_PASSWORD will not.

```
console.log(import.meta.env.VITE_SOME_KEY) // 123
console.log(import.meta.env.DB_PASSWORD) // undefined
```
-----

I think we can close this issue, @TimKieu is it solved for you?
