### ISSUE TITLE
[🐞] Creating a thumbnail slider with two Swipers does not work

### ISSUE THREAD

**Issue by b-rahmani** [QwikDev/qwik#5489]
### Which component is affected?

Qwik Runtime

### Describe the bug

I want to create a thumbnail slider in which thumbnails are shown at the bottom in smaller sizes and on click of each thumbnail the main slider shows that image in a bigger size.

Basically, I want to create [this](http://flexslider.woothemes.com/thumbnail-slider.html) using Swiper.

I use `onSwiper` from the thumbnail Swiper to get the instance. Then I want to pass it to the main Swiper. And in this step it does not work no matter what I do.

### Reproduction

https://stackblitz.com/edit/qwik-starter-xnlcwc?file=src%2Froutes%2Findex.jsx

### Steps to reproduce

- Create a new Qwik project
- Create a thumbnails Swiper
- Creat ea main Swiper
- Try to join them together, so that on click of a thumbnail, the main Swiper shows the related image

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.11 => 1.2.11 
    @builder.io/qwik-city: ^1.2.11 => 1.2.11 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by fprl** [comment]
Hey there,

May I suggest a cleaner approach? 
1. Make `SwiperElement.jsx` accept a new prop `ref`, which is of type `Signal<NoSerialize<Swiper>>`
2. Create an `instanceRef` signal in `SwiperElement.jsx`
3. Reassign `instanceRef`, so instead of doing `const swiperInstance = new Swiper(`.${name}`, mergedConfig);`, just do `instanceRef.value = noSerialize(new Swiper(`.${name}`, mergedConfig));`
4. Check if ref prop exists and reasign it: `ref.value = instanceRef.value;`
5. You can now create a ref in `index.tsx`, pass it to the `SwiperElement` component, and use the methods exposed by the instance.

**Comment by gioboa** [comment]
Hey @b-rahmani, thanks for opening this issue.
I'm closing this issue for now because @fprl suggested a valid solution.
Feel free to re-open it if it's still an issue for you.
