### ISSUE TITLE
[✨] end-to-end test of a production build

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#5798]
### Is your feature request related to a problem?

1.4.1 introduced a bug that made production builds fail to run.

### Describe the solution you'd like

We need an e2e test that builds a test app on popular targets and verifies it works correctly.

### Describe alternatives you've considered

the docs site is such a test app but the deploy to cloudflare worked, it was vercel that had an issue due to the deploy directory differing from the build location

**Comment by PatrickJS** [comment]
we should also check for each integration too the build can even work

**Comment by colelawrence** [comment]
I have a relatively complicated approach to trying to use Qwik City, and releases are always a seemingly huge gamble for me to adopt for fear of losing time. So, I end up deferring to staying on broken versions where I understand the pats that are broken rather than upgrading and risking breakages I am unfamiliar with.

**Comment by wmertens** [comment]
@colelawrence that's another way of saying that you have an awesome array of e2e tests that we should adopt. PRs welcome ;)

**Comment by maiieul** [comment]
@wmertens @PatrickJS hasn't this been done now?

**Comment by JerryWu1234** [comment]
@wmertens @maiieul
