### ISSUE TITLE
[✨] qwik-auth release cycle is not in sync with the monorepo

### ISSUE THREAD

**Issue by hosseinitabar** [QwikDev/qwik#5807]
### Is your feature request related to a problem?

As it's clear in [this commit](https://github.com/BuilderIO/qwik/pull/5790/commits/c6fe759a6327b955168031e7d4b9eea15c223eba) a bug in qwik-auth is solved by a team member of the auth.js.

It's integrated into the qwik-auth.

Yet there is no new publish for it. The last publish belongs to 4 months ago (0.1.3).

Since it's part the of qwik ecosystem, why not publishing it with the monorepo?

### Describe the solution you'd like

We would like to receive bug fixes as soon as they are available. We don't know how much should we stay behind until you publish the `@builder.io/qwik-auth` package again.

### Describe alternatives you've considered

For now, our only option is to downgrade everything and we are very upset doing it, as it's time-consuming and requires a lot of extra work from our side for many projects.

**Comment by maiieul** [comment]
The issue might not be coming from qwik-auth. I was just upgrading the X stack https://github.com/x-ploration-of-mars/x-stack and as you'll see in the repo and the live demo, it's working fine up to @auth/core 0.21.0 and vite 4.5.2. I found out that upgrading to vite 5 causes an issue with qwik-auth, same for upgrading to @auth/core 0.22.0 and later... I haven't been able to make a reproduction for it yet, but this might also be because it's deployed on the edge.

So apart from keeping @auth/core at 0.21.0 and vite at 4.5.2, you shouldn't have to stay behind. Feel free to make a reproduction and describe your issue with more details if you want further help.

**Comment by maiieul** [comment]
Ah also, qwik-auth isn't sufficiently related to qwik/core or qwik-city to have them in the same release cycle. As per my comment in https://github.com/BuilderIO/qwik/pull/5790#issuecomment-1925187201, we'll likely migrate it to @auth/qwik eventually (might be soon 👀).

**Comment by gioboa** [comment]
This is solved, we recently release a new version.
Spoiler: we are working to move the integration in the [official Next-Auth repo](https://github.com/nextauthjs/next-auth/pull/11068) :tada:
