### ISSUE TITLE
[📖] page titles have a non-standard emoji

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#6372]
### Suggestion

The emoji between the page title and the tagline is non standard and e.g. Slack renders it as a `?` (for example `
Welcome to Qwik Tutorials ? Qwik Documentation`), and my Linux shows the unknown-character glyph on the Chrome tab title.

**Comment by PatrickJS** [comment]
the problem only happens in production deployment. in preview urls it's fine

**Comment by PatrickJS** [comment]
fixed by https://github.com/QwikDev/qwik/pull/6373

The fix was to revert the polyfill for ﻿TextEncoderStream to the original one in the repo. The polyfill I used was code directly from Node.js (needed to fix Bun), but this broke the encoding for Cloudflare build/deploys. I also had tests that the old polyfill failed and the test was testing against the real one.

So, we are deploying the docs in preview and production with different settings, which means different deployment configurations for preview and production. However, we still require the old polyfill to work exactly as it did before which means it's not correct.
