### ISSUE TITLE
[🐞] Polymorphic component with applied `ref` wont update properties

### ISSUE THREAD

**Issue by KingSora** [QwikDev/qwik#6465]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm having an Polymorphic component which I'm getting the DOM element reference to via the `ref` property.
Without the `ref` property everything seems to work fine, but with the `ref` property the element begins to act in unexpected ways. In the linked example the style will not be applied. (In my app I could also observe unexpected things happen to its children)

### Reproduction

https://stackblitz.com/edit/qwik-starter-2zvxbl?file=src%2Fcomponents%2Fpoly.tsx,src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Open the example and click on the `Add Border` button.
2. After clicking the button will change its text (the state changed) but the style attribute will not be applied to the polymorphic component
3. If we remove the `ref` in the polymorphic component the expected behavior is restored.

### System Info

```shell
Shouldn't matter
```

**Comment by wmertens** [comment]
Indeed, this is a bug in v1, more specifically in how the optimizer converts the spread props, but the good news is that this should be fixed in v2.

In the meantime you can add ref to props before you spread, like so: https://qwik.dev/playground/#f=7VbBSsNAEL37FUMPpocQ8VIkpgkaFA8WpfgHboKFlga8GJL9d9%2FMzmY3otKrYC7ttLMzk5m3814EmqvVKgwKOOven9qUGMRphIY0kPFvcNJAMt%2BB7nUEYe%2BegETXuefjvkfnIjii9qLGQsKNNczXoivGb3KsKYFmScolN5wIjMWXLhUjyzLRLzBsjgr1zyqnGrWd%2B%2FcvNLzPVlPlghIcy2mapMXWhw5ZNRaNo%2FO9jjwYPNumhVfQNA8vm8c7d6ZcYizsLcVlrIf0hPw6Qw23AfkG%2Fyo2mj1PLR4%2BHJ0h4e0ZPk668KrQmKdmJbu2SLU%2Fg9kJxamoSScNIb5%2FJEOGlQqyXM%2BsikDrTQt2Mej5AgseaMnpsvsg8OKOdZBZuJ7xY61%2BDc0Y5uGSbXM4gk9vJRIPMrkxxpv%2B%2BCRzvS04VHEYBbTlpgcj73tQbfe2e%2FXDLy74wNf79r8k%2F%2BSS%2FAQ

**Comment by gioboa** [comment]
@wmertens thanks for your solution. @KingSora  it works good so I'm closing this issue.
Feel free to re-open it if it's still an issue for you.
