### ISSUE TITLE
[🐞] Breaking change introduced in 1.7.0 - `qaction` in url is appended using `routeAction` and `globalAction`

### ISSUE THREAD

**Issue by shirotech** [QwikDev/qwik#6660]
### Which component is affected?

Qwik Runtime

### Describe the bug

1.6.0 didn't have this issue

### Reproduction

> https://stackblitz.com/edit/qwik-starter-cidktr

Thanks @blecorre-mnp for the repro

### Steps to reproduce

> You can see that once you click on the submit buttons, you'll have the ```&qaction=...``` appended to the url.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 96.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.18 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.7.0 => 1.7.0
    @builder.io/qwik-city: ^1.7.0 => 1.7.0
    typescript: 5.5.3 => 5.5.3
    undici: ^6.19.2 => 6.19.2
    vite: ^5.3.3 => 5.3.3
```

**Comment by gioboa** [comment]
Can you provide a reproduction repository pls?

**Comment by blecorre-mnp** [comment]
We have the same issue here! Tried using `<Form action={...}>` as well as programmatically submitting the action, and got the `?qaction=...` appended to the browser URL. Making multiple calls / using multiple`globalAction$` on a page resulted in a new `?qaction=...&qaction=...&qaction=...&qaction=...` appended each time.

**Comment by octet-stream** [comment]
Please, provide a simple reproduction. Does it happen on every form submission or when you use redirects? Because I have similar problem when I redirect with URLSearchParams, but in my case this happens when I reuse the url from request event.

**Comment by wmertens** [comment]
Please check 1.7.1

**Comment by blecorre-mnp** [comment]
I threw this reproduction very quickly using 1.7.1: https://stackblitz.com/edit/qwik-starter-cidktr

**Comment by blecorre-mnp** [comment]
You can see that once you click on the submit buttons, you'll have the `&qaction=...` appended to the url.

**Comment by octet-stream** [comment]
Can confirm that too in very basic Qwik application. The issue occurs even without redirects.

Looks like after form submission client just navigates to `?qaction=`

I'll see if this is related to my change here: https://github.com/QwikDev/qwik/pull/6410

**Comment by octet-stream** [comment]
Yes, I think my change is the reason of this problem. I can reproduce it in my project with patched Qwik v1.5.5. I will take a look and send a PR if I find a solution.

**Comment by octet-stream** [comment]
To be clear: My fix works as intended - it checks the whole pathname for changes, including `URLSearchParams`. The problem is that when Qwik City Component decides whether to update the url or not it ignores internal Qwik params, such as `qaction` and treats them as if the URL was changed.

So, I think the solution would be to remove internal params from the url before we check whether or not to change: essentially, [this](https://github.com/QwikDev/qwik/blob/3c5e5a7614c3f64cbf89f1304dd59609053eddf0/packages/qwik-city/runtime/src/qwik-city-component.tsx#L265) object should not include the `qaction` and other internals in its `URLSearchParams`.

Also, I think internal params should also be excluded from request event object, because it I try to build a redirect url with already received params (for example, in routeAction$) I had to to this manually, and if Qwik is ever change internals I'll get unwanted params in my URLs.

**Comment by wmertens** [comment]
@octet-stream that seems a correct assessment. So you think you can implement your proposal?

**Comment by octet-stream** [comment]
Yes, at least for `QwikCityComponent`. The only question: *where* is the right place for the fix. I will take a look as soon as I have time for it (which is likely tomorrow).

Also, do we have internal search params defined somewhere? Like in an array or something, so I can just reuse to for the fix? :)

**Comment by shirotech** [comment]
> Can you provide a reproduction repository pls?

Sorry I thought it was an obvious bug that's why I thought didn't need to provide a repro.

> Yes, at least for QwikCityComponent. The only question: where is the right place for the fix. I will take a look as soon as I have time for it (which is likely tomorrow).

@octet-stream Was wondering did you got a chance to address the issue? please let me know if you require any additional information.

**Comment by octet-stream** [comment]
> please let me know if you require any additional information.

I think I have enough information, I'll work on it today.

**Comment by octet-stream** [comment]
Though I might need some help from maintainers.

My current solution is remove `qaction` after this line: https://github.com/QwikDev/qwik/blob/563ddc512a9dec38194f10914ad5988f523bd71d/packages/qwik-city/runtime/src/qwik-city-component.tsx#L265

It may be used as a quick fix for the issue, however I don't feel it is a good one.

From what I understand, the `href` parameter in `clientData` object is acquired from some virtual element (qwik city context gets it here: https://github.com/QwikDev/qwik/blob/563ddc512a9dec38194f10914ad5988f523bd71d/packages/qwik-city/runtime/src/qwik-city-component.tsx#L254), as a pathname with query params (if any). But where is this pathname being assigned? I don't understand it. Is it set somewhere from the fetch Response? If so, then where? Because I don't see anything in loadClientData function which is from what I can tell a place where actions being sent to the server and then their result is being parsed (I am referring to this code https://github.com/QwikDev/qwik/blob/563ddc512a9dec38194f10914ad5988f523bd71d/packages/qwik-city/runtime/src/use-endpoint.ts#L35), at least it gets executed where an action is sent.

/cc @wmertens @gioboa

**Comment by wmertens** [comment]
I haven't delved into that code too much yet but the context element is needed to know which route rendered a certain element. 

There are only a few q parameters used (I think maybe even only qaction, not sure, on phone) so I think your proposed solution is ok for now.

**Comment by octet-stream** [comment]
> There are only a few q parameters used (I think maybe even only qaction, not sure, on phone) so I think your proposed solution is ok for now.

Yes, all from what I can tell, all internal query params are defined here: https://github.com/QwikDev/qwik/blob/563ddc512a9dec38194f10914ad5988f523bd71d/packages/qwik-city/runtime/src/constants.ts#L9-L13

For our case I think removing qaction should be enough.

I'll send a PR with current solution then, but I'll comment on there and maybe we also come to better solution during the review.

**Comment by octet-stream** [comment]
Okay, I think I found another problem, but this might be expected (because I see this behavior in 1.5.5 too): If I disable JS and send a form, this search params will be set, when browser itself sends a form, it will request a url from `action` attribute of a form and then just render whatever the result is + change address to this URL. This can be fixed if Qwik redirects browser after the action is fired, but I'm now sure if that is intended behavior. For SPA navigation my fix works as expected. But maybe I should bring this one up in the PR.

**Comment by wmertens** [comment]
For sure your fix has to work without js as well.

**Comment by wmertens** [comment]
@octet-stream would this work? #6694

**Comment by octet-stream** [comment]
This should work too. But I would rather get keys from constants and remove them from URL object (you can copy one if side effects should not occur).

Should I update my PR or you will merge yours (if so, please add my test case)?
